name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 저장소 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. 의존성 설치
      - name: Install dependencies
        run: npm install

      # 4. 테스트 실행 (선택 사항)
    #   - name: Run tests
    #     run: npm test

      # 5. 빌드
      - name: Build project
        run: npm run build

      # 6. Vercel에 배포
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # GitHub Secrets에 저장된 토큰
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  # 조직 ID
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}  # 프로젝트 ID
          vercel-args: '--prod'  # 프로덕션 배포 설정